package com.proyecto.model;
// Generated 06-08-2013 11:30:49 AM by Hibernate Tools 3.2.1.GA



/**
 * CargoId generated by hbm2java
 */
public class CargoId  implements java.io.Serializable {


     private String iddepartamento;
     private String iddocente;
     private String idcargo;

    public CargoId() {
    }

    public CargoId(String iddepartamento, String iddocente, String idcargo) {
       this.iddepartamento = iddepartamento;
       this.iddocente = iddocente;
       this.idcargo = idcargo;
    }
   
    public String getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(String iddocente) {
        this.iddocente = iddocente;
    }
    public String getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(String idcargo) {
        this.idcargo = idcargo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CargoId) ) return false;
		 CargoId castOther = ( CargoId ) other; 
         
		 return ( (this.getIddepartamento()==castOther.getIddepartamento()) || ( this.getIddepartamento()!=null && castOther.getIddepartamento()!=null && this.getIddepartamento().equals(castOther.getIddepartamento()) ) )
 && ( (this.getIddocente()==castOther.getIddocente()) || ( this.getIddocente()!=null && castOther.getIddocente()!=null && this.getIddocente().equals(castOther.getIddocente()) ) )
 && ( (this.getIdcargo()==castOther.getIdcargo()) || ( this.getIdcargo()!=null && castOther.getIdcargo()!=null && this.getIdcargo().equals(castOther.getIdcargo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIddepartamento() == null ? 0 : this.getIddepartamento().hashCode() );
         result = 37 * result + ( getIddocente() == null ? 0 : this.getIddocente().hashCode() );
         result = 37 * result + ( getIdcargo() == null ? 0 : this.getIdcargo().hashCode() );
         return result;
   }   


}


