package com.proyecto.model;
// Generated 06-08-2013 11:30:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private String iddepartamento;
     private String nombredepartamento;
     private String descripciondepartamento;
     private Set<Docente> docentes = new HashSet<Docente>(0);
     private Set<Cargo> cargos = new HashSet<Cargo>(0);

    public Departamento() {
    }

	
    public Departamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Departamento(String iddepartamento, String nombredepartamento, String descripciondepartamento, Set<Docente> docentes, Set<Cargo> cargos) {
       this.iddepartamento = iddepartamento;
       this.nombredepartamento = nombredepartamento;
       this.descripciondepartamento = descripciondepartamento;
       this.docentes = docentes;
       this.cargos = cargos;
    }
   
    public String getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getNombredepartamento() {
        return this.nombredepartamento;
    }
    
    public void setNombredepartamento(String nombredepartamento) {
        this.nombredepartamento = nombredepartamento;
    }
    public String getDescripciondepartamento() {
        return this.descripciondepartamento;
    }
    
    public void setDescripciondepartamento(String descripciondepartamento) {
        this.descripciondepartamento = descripciondepartamento;
    }
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }
    public Set<Cargo> getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set<Cargo> cargos) {
        this.cargos = cargos;
    }




}


