package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private String iddocente;
     private Departamento departamento;
     private String nombredocente;
     private String apellidodocente;
     private String especialidad;
     private String cargo;
     private String email;
     private Set<Propuesta> propuestas = new HashSet<Propuesta>(0);
     private Set<Materia> materias = new HashSet<Materia>(0);
     private Set<Cargo> cargos = new HashSet<Cargo>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Docente() {
    }

	
    public Docente(String iddocente, String nombredocente, String apellidodocente, String cargo, String email) {
        this.iddocente = iddocente;
        this.nombredocente = nombredocente;
        this.apellidodocente = apellidodocente;
        this.cargo = cargo;
        this.email = email;
    }
    public Docente(String iddocente, Departamento departamento, String nombredocente, String apellidodocente, String especialidad, String cargo, String email, Set<Propuesta> propuestas, Set<Materia> materias, Set<Cargo> cargos, Set<Usuario> usuarios) {
       this.iddocente = iddocente;
       this.departamento = departamento;
       this.nombredocente = nombredocente;
       this.apellidodocente = apellidodocente;
       this.especialidad = especialidad;
       this.cargo = cargo;
       this.email = email;
       this.propuestas = propuestas;
       this.materias = materias;
       this.cargos = cargos;
       this.usuarios = usuarios;
    }
   
    public String getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(String iddocente) {
        this.iddocente = iddocente;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombredocente() {
        return this.nombredocente;
    }
    
    public void setNombredocente(String nombredocente) {
        this.nombredocente = nombredocente;
    }
    public String getApellidodocente() {
        return this.apellidodocente;
    }
    
    public void setApellidodocente(String apellidodocente) {
        this.apellidodocente = apellidodocente;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Propuesta> getPropuestas() {
        return this.propuestas;
    }
    
    public void setPropuestas(Set<Propuesta> propuestas) {
        this.propuestas = propuestas;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }
    public Set<Cargo> getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set<Cargo> cargos) {
        this.cargos = cargos;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


