package com.proyecto.model;
// Generated 06-08-2013 11:30:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private String idhorario;
     private Materia materia;
     private Local local;
     private String dia;
     private Date horainicio;
     private Date horafin;

    public Horario() {
    }

	
    public Horario(String idhorario) {
        this.idhorario = idhorario;
    }
    public Horario(String idhorario, Materia materia, Local local, String dia, Date horainicio, Date horafin) {
       this.idhorario = idhorario;
       this.materia = materia;
       this.local = local;
       this.dia = dia;
       this.horainicio = horainicio;
       this.horafin = horafin;
    }
   
    public String getIdhorario() {
        return this.idhorario;
    }
    
    public void setIdhorario(String idhorario) {
        this.idhorario = idhorario;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }




}


