package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private String idlocal;
     private String nombrelocal;
     private BigDecimal capacidad;
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public Local() {
    }

	
    public Local(String idlocal) {
        this.idlocal = idlocal;
    }
    public Local(String idlocal, String nombrelocal, BigDecimal capacidad, Set<Horario> horarios) {
       this.idlocal = idlocal;
       this.nombrelocal = nombrelocal;
       this.capacidad = capacidad;
       this.horarios = horarios;
    }
   
    public String getIdlocal() {
        return this.idlocal;
    }
    
    public void setIdlocal(String idlocal) {
        this.idlocal = idlocal;
    }
    public String getNombrelocal() {
        return this.nombrelocal;
    }
    
    public void setNombrelocal(String nombrelocal) {
        this.nombrelocal = nombrelocal;
    }
    public BigDecimal getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(BigDecimal capacidad) {
        this.capacidad = capacidad;
    }
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


