package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private MateriaId id;
     private Docente docente;
     private Propuesta propuesta;
     private Pensum pensum;
     private String nombremateria;
     private BigDecimal uv;
     private BigDecimal cicloimparte;
     private String tipomateria;
     private BigDecimal numhorasprac;
     private BigDecimal numhorasteo;
     private Set<Prerrequisito> prerrequisitos = new HashSet<Prerrequisito>(0);
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public Materia() {
    }

	
    public Materia(MateriaId id, Propuesta propuesta) {
        this.id = id;
        this.propuesta = propuesta;
    }
    public Materia(MateriaId id, Docente docente, Propuesta propuesta, Pensum pensum, String nombremateria, BigDecimal uv, BigDecimal cicloimparte, String tipomateria, BigDecimal numhorasprac, BigDecimal numhorasteo, Set<Prerrequisito> prerrequisitos, Set<Horario> horarios) {
       this.id = id;
       this.docente = docente;
       this.propuesta = propuesta;
       this.pensum = pensum;
       this.nombremateria = nombremateria;
       this.uv = uv;
       this.cicloimparte = cicloimparte;
       this.tipomateria = tipomateria;
       this.numhorasprac = numhorasprac;
       this.numhorasteo = numhorasteo;
       this.prerrequisitos = prerrequisitos;
       this.horarios = horarios;
    }
   
    public MateriaId getId() {
        return this.id;
    }
    
    public void setId(MateriaId id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Propuesta getPropuesta() {
        return this.propuesta;
    }
    
    public void setPropuesta(Propuesta propuesta) {
        this.propuesta = propuesta;
    }
    public Pensum getPensum() {
        return this.pensum;
    }
    
    public void setPensum(Pensum pensum) {
        this.pensum = pensum;
    }
    public String getNombremateria() {
        return this.nombremateria;
    }
    
    public void setNombremateria(String nombremateria) {
        this.nombremateria = nombremateria;
    }
    public BigDecimal getUv() {
        return this.uv;
    }
    
    public void setUv(BigDecimal uv) {
        this.uv = uv;
    }
    public BigDecimal getCicloimparte() {
        return this.cicloimparte;
    }
    
    public void setCicloimparte(BigDecimal cicloimparte) {
        this.cicloimparte = cicloimparte;
    }
    public String getTipomateria() {
        return this.tipomateria;
    }
    
    public void setTipomateria(String tipomateria) {
        this.tipomateria = tipomateria;
    }
    public BigDecimal getNumhorasprac() {
        return this.numhorasprac;
    }
    
    public void setNumhorasprac(BigDecimal numhorasprac) {
        this.numhorasprac = numhorasprac;
    }
    public BigDecimal getNumhorasteo() {
        return this.numhorasteo;
    }
    
    public void setNumhorasteo(BigDecimal numhorasteo) {
        this.numhorasteo = numhorasteo;
    }
    public Set<Prerrequisito> getPrerrequisitos() {
        return this.prerrequisitos;
    }
    
    public void setPrerrequisitos(Set<Prerrequisito> prerrequisitos) {
        this.prerrequisitos = prerrequisitos;
    }
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


