package com.proyecto.model;
// Generated 06-08-2013 11:30:49 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pensum generated by hbm2java
 */
public class Pensum  implements java.io.Serializable {


     private String idpensum;
     private String nombrecarrera;
     private BigDecimal anioaprobacion;
     private Set<Materia> materias = new HashSet<Materia>(0);

    public Pensum() {
    }

	
    public Pensum(String idpensum) {
        this.idpensum = idpensum;
    }
    public Pensum(String idpensum, String nombrecarrera, BigDecimal anioaprobacion, Set<Materia> materias) {
       this.idpensum = idpensum;
       this.nombrecarrera = nombrecarrera;
       this.anioaprobacion = anioaprobacion;
       this.materias = materias;
    }
   
    public String getIdpensum() {
        return this.idpensum;
    }
    
    public void setIdpensum(String idpensum) {
        this.idpensum = idpensum;
    }
    public String getNombrecarrera() {
        return this.nombrecarrera;
    }
    
    public void setNombrecarrera(String nombrecarrera) {
        this.nombrecarrera = nombrecarrera;
    }
    public BigDecimal getAnioaprobacion() {
        return this.anioaprobacion;
    }
    
    public void setAnioaprobacion(BigDecimal anioaprobacion) {
        this.anioaprobacion = anioaprobacion;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }




}


