package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private BigDecimal idpermiso;
     private Usuario usuario;
     private String tabla;
     private BigDecimal create;
     private BigDecimal read;
     private BigDecimal update;
     private BigDecimal delete;

    public Permisos() {
    }

    public Permisos(BigDecimal idpermiso, Usuario usuario, String tabla, BigDecimal create, BigDecimal read, BigDecimal update, BigDecimal delete) {
       this.idpermiso = idpermiso;
       this.usuario = usuario;
       this.tabla = tabla;
       this.create = create;
       this.read = read;
       this.update = update;
       this.delete = delete;
    }
   
    public BigDecimal getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(BigDecimal idpermiso) {
        this.idpermiso = idpermiso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
    public BigDecimal getCreate() {
        return this.create;
    }
    
    public void setCreate(BigDecimal create) {
        this.create = create;
    }
    public BigDecimal getRead() {
        return this.read;
    }
    
    public void setRead(BigDecimal read) {
        this.read = read;
    }
    public BigDecimal getUpdate() {
        return this.update;
    }
    
    public void setUpdate(BigDecimal update) {
        this.update = update;
    }
    public BigDecimal getDelete() {
        return this.delete;
    }
    
    public void setDelete(BigDecimal delete) {
        this.delete = delete;
    }




}


