package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA



/**
 * PrerrequisitoId generated by hbm2java
 */
public class PrerrequisitoId  implements java.io.Serializable {


     private String idpropuesta;
     private String codigomateria;

    public PrerrequisitoId() {
    }

    public PrerrequisitoId(String idpropuesta, String codigomateria) {
       this.idpropuesta = idpropuesta;
       this.codigomateria = codigomateria;
    }
   
    public String getIdpropuesta() {
        return this.idpropuesta;
    }
    
    public void setIdpropuesta(String idpropuesta) {
        this.idpropuesta = idpropuesta;
    }
    public String getCodigomateria() {
        return this.codigomateria;
    }
    
    public void setCodigomateria(String codigomateria) {
        this.codigomateria = codigomateria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrerrequisitoId) ) return false;
		 PrerrequisitoId castOther = ( PrerrequisitoId ) other; 
         
		 return ( (this.getIdpropuesta()==castOther.getIdpropuesta()) || ( this.getIdpropuesta()!=null && castOther.getIdpropuesta()!=null && this.getIdpropuesta().equals(castOther.getIdpropuesta()) ) )
 && ( (this.getCodigomateria()==castOther.getCodigomateria()) || ( this.getCodigomateria()!=null && castOther.getCodigomateria()!=null && this.getCodigomateria().equals(castOther.getCodigomateria()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpropuesta() == null ? 0 : this.getIdpropuesta().hashCode() );
         result = 37 * result + ( getCodigomateria() == null ? 0 : this.getCodigomateria().hashCode() );
         return result;
   }   


}


