package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Propuesta generated by hbm2java
 */
public class Propuesta  implements java.io.Serializable {


     private String idpropuesta;
     private Docente docente;
     private Cargo cargo;
     private Date fechapropuesta;
     private Clob detalle;
     private Clob justificacion;
     private BigDecimal aprobadojefe;
     private BigDecimal aprobadodirector;
     private BigDecimal aprobadojunta;
     private Set<Recursos> recursoses = new HashSet<Recursos>(0);
     private Set<Materia> materias = new HashSet<Materia>(0);

    public Propuesta() {
    }

	
    public Propuesta(String idpropuesta, Date fechapropuesta, Clob detalle, Clob justificacion) {
        this.idpropuesta = idpropuesta;
        this.fechapropuesta = fechapropuesta;
        this.detalle = detalle;
        this.justificacion = justificacion;
    }
    public Propuesta(String idpropuesta, Docente docente, Cargo cargo, Date fechapropuesta, Clob detalle, Clob justificacion, BigDecimal aprobadojefe, BigDecimal aprobadodirector, BigDecimal aprobadojunta, Set<Recursos> recursoses, Set<Materia> materias) {
       this.idpropuesta = idpropuesta;
       this.docente = docente;
       this.cargo = cargo;
       this.fechapropuesta = fechapropuesta;
       this.detalle = detalle;
       this.justificacion = justificacion;
       this.aprobadojefe = aprobadojefe;
       this.aprobadodirector = aprobadodirector;
       this.aprobadojunta = aprobadojunta;
       this.recursoses = recursoses;
       this.materias = materias;
    }
   
    public String getIdpropuesta() {
        return this.idpropuesta;
    }
    
    public void setIdpropuesta(String idpropuesta) {
        this.idpropuesta = idpropuesta;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Date getFechapropuesta() {
        return this.fechapropuesta;
    }
    
    public void setFechapropuesta(Date fechapropuesta) {
        this.fechapropuesta = fechapropuesta;
    }
    public Clob getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(Clob detalle) {
        this.detalle = detalle;
    }
    public Clob getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(Clob justificacion) {
        this.justificacion = justificacion;
    }
    public BigDecimal getAprobadojefe() {
        return this.aprobadojefe;
    }
    
    public void setAprobadojefe(BigDecimal aprobadojefe) {
        this.aprobadojefe = aprobadojefe;
    }
    public BigDecimal getAprobadodirector() {
        return this.aprobadodirector;
    }
    
    public void setAprobadodirector(BigDecimal aprobadodirector) {
        this.aprobadodirector = aprobadodirector;
    }
    public BigDecimal getAprobadojunta() {
        return this.aprobadojunta;
    }
    
    public void setAprobadojunta(BigDecimal aprobadojunta) {
        this.aprobadojunta = aprobadojunta;
    }
    public Set<Recursos> getRecursoses() {
        return this.recursoses;
    }
    
    public void setRecursoses(Set<Recursos> recursoses) {
        this.recursoses = recursoses;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }




}


