package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.sql.Clob;

/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private String idrecursos;
     private Propuesta propuesta;
     private String nombrerecursos;
     private Clob descripcionrecursos;

    public Recursos() {
    }

	
    public Recursos(String idrecursos) {
        this.idrecursos = idrecursos;
    }
    public Recursos(String idrecursos, Propuesta propuesta, String nombrerecursos, Clob descripcionrecursos) {
       this.idrecursos = idrecursos;
       this.propuesta = propuesta;
       this.nombrerecursos = nombrerecursos;
       this.descripcionrecursos = descripcionrecursos;
    }
   
    public String getIdrecursos() {
        return this.idrecursos;
    }
    
    public void setIdrecursos(String idrecursos) {
        this.idrecursos = idrecursos;
    }
    public Propuesta getPropuesta() {
        return this.propuesta;
    }
    
    public void setPropuesta(Propuesta propuesta) {
        this.propuesta = propuesta;
    }
    public String getNombrerecursos() {
        return this.nombrerecursos;
    }
    
    public void setNombrerecursos(String nombrerecursos) {
        this.nombrerecursos = nombrerecursos;
    }
    public Clob getDescripcionrecursos() {
        return this.descripcionrecursos;
    }
    
    public void setDescripcionrecursos(Clob descripcionrecursos) {
        this.descripcionrecursos = descripcionrecursos;
    }




}


