package com.proyecto.model;
// Generated 06-08-2013 11:30:49 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idusuario;
     private String password;
     private BigDecimal tipousuario;
     private BigDecimal activo;
     private Set<Docente> docentes = new HashSet<Docente>(0);

    public Usuario() {
    }

	
    public Usuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(String idusuario, String password, BigDecimal tipousuario, BigDecimal activo, Set<Docente> docentes) {
       this.idusuario = idusuario;
       this.password = password;
       this.tipousuario = tipousuario;
       this.activo = activo;
       this.docentes = docentes;
    }
   
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(BigDecimal tipousuario) {
        this.tipousuario = tipousuario;
    }
    public BigDecimal getActivo() {
        return this.activo;
    }
    
    public void setActivo(BigDecimal activo) {
        this.activo = activo;
    }
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }




}


