package com.proyecto.model;
// Generated 06-08-2013 12:51:34 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idusuario;
     private Docente docente;
     private String password;
     private String tipousuario;
     private BigDecimal estado;
     private Set<Permisos> permisoses = new HashSet<Permisos>(0);

    public Usuario() {
    }

	
    public Usuario(String idusuario, String password, String tipousuario, BigDecimal estado) {
        this.idusuario = idusuario;
        this.password = password;
        this.tipousuario = tipousuario;
        this.estado = estado;
    }
    public Usuario(String idusuario, Docente docente, String password, String tipousuario, BigDecimal estado, Set<Permisos> permisoses) {
       this.idusuario = idusuario;
       this.docente = docente;
       this.password = password;
       this.tipousuario = tipousuario;
       this.estado = estado;
       this.permisoses = permisoses;
    }
   
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
    public Set<Permisos> getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set<Permisos> permisoses) {
        this.permisoses = permisoses;
    }




}


